version: '3'
services:
  redis:
    container_name: redis
    restart: always
    image: redis:6.2
    ports:
      - 6379:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./:/etc/redis
      - ./data/:/data
